server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/report?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      connection-test-query: SELECT 1
      minimum-idle: 10
      idle-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true